{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 2}, "tests": {"0": {"status": "ERROR", "message": "print_time = '22:20:18.302166', create_file_txt = True\n\n    @pytest.fixture()\n    def write_stat_file(print_time, create_file_txt):\n        if create_file_txt:\n            # with open(data['filename'], 'w', encoding='utf-8') as f:\n            #     f.write(str(print_time))\n            #     f.write(str(data['count']))\n            #     f.write(str(data['size_of_file']))\n    \n            file = open('{}/{}'.format(data['folder_tst'], data['filename']), 'a')\n            # file.writelines('Test time:  ')\n            # file.write(str(print_time))\n            # file.write('Files quantity:  ')\n            # file.write(str(data['count']))\n            # file.write('Size of file:  ')\n            # file.write(str(data['size_of_file']))\n            # file.write(' ')\n>           file.write(file(\"cd {} ./; cat{}\".format(data['proc'], data['loadavg']), \"\"))\nE           TypeError: '_io.TextIOWrapper' object is not callable\n\nconftest.py:110: TypeError\n", "test_name": "test_step8", "rerun": "0"}, "1": {"status": "ERROR", "message": "print_time = '22:20:18.327176', create_file_txt = True\n\n    @pytest.fixture()\n    def write_stat_file(print_time, create_file_txt):\n        if create_file_txt:\n            # with open(data['filename'], 'w', encoding='utf-8') as f:\n            #     f.write(str(print_time))\n            #     f.write(str(data['count']))\n            #     f.write(str(data['size_of_file']))\n    \n            file = open('{}/{}'.format(data['folder_tst'], data['filename']), 'a')\n            # file.writelines('Test time:  ')\n            # file.write(str(print_time))\n            # file.write('Files quantity:  ')\n            # file.write(str(data['count']))\n            # file.write('Size of file:  ')\n            # file.write(str(data['size_of_file']))\n            # file.write(' ')\n>           file.write(file(\"cd {} ./; cat{}\".format(data['proc'], data['loadavg']), \"\"))\nE           TypeError: '_io.TextIOWrapper' object is not callable\n\nconftest.py:110: TypeError\n", "test_name": "test_step9", "rerun": "0"}}, "suite_name": "test_7z_negative.py"}, "1": {"suite_name": "test_7z_positive.py", "tests": {"0": {"status": "ERROR", "message": "print_time = '22:20:18.336510', create_file_txt = True\n\n    @pytest.fixture()\n    def write_stat_file(print_time, create_file_txt):\n        if create_file_txt:\n            # with open(data['filename'], 'w', encoding='utf-8') as f:\n            #     f.write(str(print_time))\n            #     f.write(str(data['count']))\n            #     f.write(str(data['size_of_file']))\n    \n            file = open('{}/{}'.format(data['folder_tst'], data['filename']), 'a')\n            # file.writelines('Test time:  ')\n            # file.write(str(print_time))\n            # file.write('Files quantity:  ')\n            # file.write(str(data['count']))\n            # file.write('Size of file:  ')\n            # file.write(str(data['size_of_file']))\n            # file.write(' ')\n>           file.write(file(\"cd {} ./; cat{}\".format(data['proc'], data['loadavg']), \"\"))\nE           TypeError: '_io.TextIOWrapper' object is not callable\n\nconftest.py:110: TypeError\n", "test_name": "test_step1", "rerun": "0"}, "1": {"status": "ERROR", "message": "print_time = '22:20:18.383310', create_file_txt = True\n\n    @pytest.fixture()\n    def write_stat_file(print_time, create_file_txt):\n        if create_file_txt:\n            # with open(data['filename'], 'w', encoding='utf-8') as f:\n            #     f.write(str(print_time))\n            #     f.write(str(data['count']))\n            #     f.write(str(data['size_of_file']))\n    \n            file = open('{}/{}'.format(data['folder_tst'], data['filename']), 'a')\n            # file.writelines('Test time:  ')\n            # file.write(str(print_time))\n            # file.write('Files quantity:  ')\n            # file.write(str(data['count']))\n            # file.write('Size of file:  ')\n            # file.write(str(data['size_of_file']))\n            # file.write(' ')\n>           file.write(file(\"cd {} ./; cat{}\".format(data['proc'], data['loadavg']), \"\"))\nE           TypeError: '_io.TextIOWrapper' object is not callable\n\nconftest.py:110: TypeError\n", "test_name": "test_step2", "rerun": "0"}, "2": {"status": "ERROR", "message": "print_time = '22:20:18.424002', create_file_txt = True\n\n    @pytest.fixture()\n    def write_stat_file(print_time, create_file_txt):\n        if create_file_txt:\n            # with open(data['filename'], 'w', encoding='utf-8') as f:\n            #     f.write(str(print_time))\n            #     f.write(str(data['count']))\n            #     f.write(str(data['size_of_file']))\n    \n            file = open('{}/{}'.format(data['folder_tst'], data['filename']), 'a')\n            # file.writelines('Test time:  ')\n            # file.write(str(print_time))\n            # file.write('Files quantity:  ')\n            # file.write(str(data['count']))\n            # file.write('Size of file:  ')\n            # file.write(str(data['size_of_file']))\n            # file.write(' ')\n>           file.write(file(\"cd {} ./; cat{}\".format(data['proc'], data['loadavg']), \"\"))\nE           TypeError: '_io.TextIOWrapper' object is not callable\n\nconftest.py:110: TypeError\n", "test_name": "test_step3", "rerun": "0"}, "3": {"status": "ERROR", "message": "print_time = '22:20:18.433260', create_file_txt = True\n\n    @pytest.fixture()\n    def write_stat_file(print_time, create_file_txt):\n        if create_file_txt:\n            # with open(data['filename'], 'w', encoding='utf-8') as f:\n            #     f.write(str(print_time))\n            #     f.write(str(data['count']))\n            #     f.write(str(data['size_of_file']))\n    \n            file = open('{}/{}'.format(data['folder_tst'], data['filename']), 'a')\n            # file.writelines('Test time:  ')\n            # file.write(str(print_time))\n            # file.write('Files quantity:  ')\n            # file.write(str(data['count']))\n            # file.write('Size of file:  ')\n            # file.write(str(data['size_of_file']))\n            # file.write(' ')\n>           file.write(file(\"cd {} ./; cat{}\".format(data['proc'], data['loadavg']), \"\"))\nE           TypeError: '_io.TextIOWrapper' object is not callable\n\nconftest.py:110: TypeError\n", "test_name": "test_step4", "rerun": "0"}, "4": {"status": "ERROR", "message": "print_time = '22:20:18.477440', create_file_txt = True\n\n    @pytest.fixture()\n    def write_stat_file(print_time, create_file_txt):\n        if create_file_txt:\n            # with open(data['filename'], 'w', encoding='utf-8') as f:\n            #     f.write(str(print_time))\n            #     f.write(str(data['count']))\n            #     f.write(str(data['size_of_file']))\n    \n            file = open('{}/{}'.format(data['folder_tst'], data['filename']), 'a')\n            # file.writelines('Test time:  ')\n            # file.write(str(print_time))\n            # file.write('Files quantity:  ')\n            # file.write(str(data['count']))\n            # file.write('Size of file:  ')\n            # file.write(str(data['size_of_file']))\n            # file.write(' ')\n>           file.write(file(\"cd {} ./; cat{}\".format(data['proc'], data['loadavg']), \"\"))\nE           TypeError: '_io.TextIOWrapper' object is not callable\n\nconftest.py:110: TypeError\n", "test_name": "test_step5", "rerun": "0"}, "5": {"status": "ERROR", "message": "print_time = '22:20:18.519466', create_file_txt = True\n\n    @pytest.fixture()\n    def write_stat_file(print_time, create_file_txt):\n        if create_file_txt:\n            # with open(data['filename'], 'w', encoding='utf-8') as f:\n            #     f.write(str(print_time))\n            #     f.write(str(data['count']))\n            #     f.write(str(data['size_of_file']))\n    \n            file = open('{}/{}'.format(data['folder_tst'], data['filename']), 'a')\n            # file.writelines('Test time:  ')\n            # file.write(str(print_time))\n            # file.write('Files quantity:  ')\n            # file.write(str(data['count']))\n            # file.write('Size of file:  ')\n            # file.write(str(data['size_of_file']))\n            # file.write(' ')\n>           file.write(file(\"cd {} ./; cat{}\".format(data['proc'], data['loadavg']), \"\"))\nE           TypeError: '_io.TextIOWrapper' object is not callable\n\nconftest.py:110: TypeError\n", "test_name": "test_step6", "rerun": "0"}, "6": {"status": "ERROR", "message": "print_time = '22:20:18.572531', create_file_txt = True\n\n    @pytest.fixture()\n    def write_stat_file(print_time, create_file_txt):\n        if create_file_txt:\n            # with open(data['filename'], 'w', encoding='utf-8') as f:\n            #     f.write(str(print_time))\n            #     f.write(str(data['count']))\n            #     f.write(str(data['size_of_file']))\n    \n            file = open('{}/{}'.format(data['folder_tst'], data['filename']), 'a')\n            # file.writelines('Test time:  ')\n            # file.write(str(print_time))\n            # file.write('Files quantity:  ')\n            # file.write(str(data['count']))\n            # file.write('Size of file:  ')\n            # file.write(str(data['size_of_file']))\n            # file.write(' ')\n>           file.write(file(\"cd {} ./; cat{}\".format(data['proc'], data['loadavg']), \"\"))\nE           TypeError: '_io.TextIOWrapper' object is not callable\n\nconftest.py:110: TypeError\n", "test_name": "test_step7", "rerun": "0"}, "7": {"status": "ERROR", "message": "print_time = '22:20:18.581343', create_file_txt = True\n\n    @pytest.fixture()\n    def write_stat_file(print_time, create_file_txt):\n        if create_file_txt:\n            # with open(data['filename'], 'w', encoding='utf-8') as f:\n            #     f.write(str(print_time))\n            #     f.write(str(data['count']))\n            #     f.write(str(data['size_of_file']))\n    \n            file = open('{}/{}'.format(data['folder_tst'], data['filename']), 'a')\n            # file.writelines('Test time:  ')\n            # file.write(str(print_time))\n            # file.write('Files quantity:  ')\n            # file.write(str(data['count']))\n            # file.write('Size of file:  ')\n            # file.write(str(data['size_of_file']))\n            # file.write(' ')\n>           file.write(file(\"cd {} ./; cat{}\".format(data['proc'], data['loadavg']), \"\"))\nE           TypeError: '_io.TextIOWrapper' object is not callable\n\nconftest.py:110: TypeError\n", "test_name": "test_step10", "rerun": "0"}}, "status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 8}}}}, "date": "April 27, 2023", "start_time": 1682623218.5812576, "total_suite": 2, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "10", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "10"}